# Generated by Django 4.2.6 on 2023-11-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='TipoPoliza',
        ),
        migrations.AddField(
            model_name='usuario',
            name='registro',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
