# Generated by Django 4.2.6 on 2023-11-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_usuario_tipopoliza_usuario_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='peso',
        ),
    ]
